# Site settings
name: Drew Naylor's Website
email: 
author: DrewNaylor

keywords: Naylor, Drew, Drew Naylor, Emulation, Emulators, Drew Naylor Emulation
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the official website of Drew Naylor! In 2016 I decided to port my website from Weebly to GitHub Pages. Please enjoy your stay.

baseurl: https://drew-naylor.com
url: https://drew-naylor.com
enforce_ssl: drew-naylor.com

header: yes
header_sm: banners/Drew-Naylors-Website_banner-Small.jpg
header_med: banners/Drew-Naylors-Website_banner-Medium.jpg
header_large: banners/Drew-Naylors-Website_banner-Large.jpg
header_xl: banners/Drew-Naylors-Website_banner-XL.jpg


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:

  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
